/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jDgOperation.java
 *
 * Created on 17.06.2011, 19:33:06
 */
package Android;

import Dict.IExceptionOccured;
import Dict.IProgressChanged;
import Dict.ProgressChangedEventArgs;
import javax.swing.JOptionPane;

/**
 *
 * @author Николай
 * форма для отображения прогресса
 */
public class jDgOperation extends javax.swing.JDialog implements IExceptionOccured,IProgressChanged {

    private boolean isCancel=false;
    private boolean isFinish=false;
    /** Creates new form jDgOperation */
    public jDgOperation(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    //реализует функцию - делегат для интерфейса IProgressChanged,
    //отображает изменение прогресса
    public void ProgressChanged(ProgressChangedEventArgs e) 
    {
        
        
        if (e.getFinish()) 
        {
            if (this.isCancel)
            {
                JOptionPane.showMessageDialog(null,"Операция прервана"); 
                this.setVisible(false);
                return;
            }
            isFinish=true;
            this.jbCancel.setText("Готово");
            return;
        }
        
        if (this.isCancel)
        {
            e.setCancel(isCancel);
            return;
        }
        this.jlAction.setText(e.getAction());
        this.jlInfo.setText(e.getInfo());
        this.jpbOperationProgress.setMaximum(e.getAllCount());
        this.jpbOperationProgress.setValue(e.getCount());
        
       // this.setVisible(true);
        
        
        
    }
    //реализует функцию - делегат для интерфейса IExceptionOccured,
    //отображает возникновение исключения
    public void ExceptionOccured(Exception ex)
    {
        JOptionPane.showMessageDialog(null,ex.getMessage()); 
        this.setVisible(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlAction = new javax.swing.JLabel();
        jpbOperationProgress = new javax.swing.JProgressBar();
        jlInfo = new javax.swing.JLabel();
        jbCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setModal(true);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Android.JavaQuest.class).getContext().getResourceMap(jDgOperation.class);
        jlAction.setText(resourceMap.getString("jlAction.text")); // NOI18N
        jlAction.setName("jlAction"); // NOI18N

        jpbOperationProgress.setName("jpbOperationProgress"); // NOI18N

        jlInfo.setText(resourceMap.getString("jlInfo.text")); // NOI18N
        jlInfo.setName("jlInfo"); // NOI18N

        jbCancel.setText(resourceMap.getString("jbCancel.text")); // NOI18N
        jbCancel.setName("jbCancel"); // NOI18N
        jbCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlAction)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jlInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbCancel))
                        .addComponent(jpbOperationProgress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlAction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpbOperationProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlInfo)
                    .addComponent(jbCancel))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCancelMouseClicked
        // TODO add your handling code here:
       if (!this.isFinish)
       {
            this.isCancel=true;
            this.jlAction.setText("Прерываю действие...");
       }
       else this.setVisible(false);
        
    }//GEN-LAST:event_jbCancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                jDgOperation dialog = new jDgOperation(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCancel;
    private javax.swing.JLabel jlAction;
    private javax.swing.JLabel jlInfo;
    private javax.swing.JProgressBar jpbOperationProgress;
    // End of variables declaration//GEN-END:variables

   
}
